on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04    # supported: ubuntu-16.04 and ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: tomasnorre/github-action-setup-ddev@feature/custom-ddev-dir
        with:
          ddevDir: ".devbox"
      # example: composer install
      - run: |
        cd .devbox
        ddev composer install